name: 'Set up Emacs'
description: 'Install a specific Emacs version for use in your workflow.'
author: 'Steve Purcell'
inputs:
  version:
    description: 'The version of Emacs to install, e.g. "24.3", or "snapshot" for a recent development version.'
    default: '26.3'
runs:
  using: 'node12'
  main: 'dist/index.js'
